kind: ServiceAccount
apiVersion: v1
metadata:
  name: calculator-account
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: kube-system
  name: calculator-service-reader
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
  - nonResourceURLs:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: calculator-service-reader
subjects:
  - kind: ServiceAccount
    # Reference to ServiceAccount kind's `metadata.name`
    name: calculator-account
    # Reference to ServiceAccount kind's `metadata.namespace`
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: calculator-service-reader
  apiGroup: rbac.authorization.k8s.io